---
node_exporter_version: "1.8.2"
node_exporter_port: 9100
node_exporter_collectors_extra:
  - systemd
  - processes
  - textfile
node_exporter_textfile_dir: /var/lib/node_exporter/textfile_collector

promtail_version: "3.2.1"
promtail_port: 9080
promtail_loki_url: ""
promtail_positions_file: /var/lib/promtail/positions.yaml
