---
# Development tier — single collapsed node, intentionally cheap.
all:
  vars:
    env_tier: dev
    site_name: dc-primary
  children:
    loadbalancers:
      hosts:
        dev-all-01: { ansible_host: 10.10.10.11 }
    appservers:
      hosts:
        dev-all-01: { ansible_host: 10.10.10.11, app_node_id: 1 }
    tomcat_nodes:
      hosts:
        dev-all-01: { ansible_host: 10.10.10.11 }
    databases:
      children:
        db_primary:
          hosts:
            dev-all-01: { ansible_host: 10.10.10.11 }
    monitoring:
      hosts:
        dev-all-01: { ansible_host: 10.10.10.11 }
    platform:
      children:
        loadbalancers:
        appservers:
        tomcat_nodes:
        databases:
        monitoring:
